@contentType = application/json

### ======== login ===========

# @name login
POST http://{{host}}/api/login HTTP/1.1
content-type: {{contentType}}

{
    "email": "333@qq.com",
    "password": "123456"
}

### 
# 登录成功后的 token
@authToken = Bearer {{login.response.body.$.data.token}}

### ======== user ===========

GET http://{{host}}/api/users?page=2&size=2 HTTP/1.1
Authorization: {{authToken}}

###

POST http://{{host}}/api/users HTTP/1.1
content-type: {{contentType}}
Authorization: {{authToken}}

{
    "name": "test6",  
    "email": "6@qq.com",
    "password": "123456",
    "password_confirmation": "123456"
}

###

GET http://{{host}}/api/users/1 HTTP/1.1
Authorization: {{authToken}}

###

PUT http://{{host}}/api/users/1 HTTP/1.1
content-type: {{contentType}}
Authorization: {{authToken}}

{
    "name": "test111",  
    "password": "123456",
    "password_confirmation": "123456"
}

###

DELETE  http://{{host}}/api/users/4 HTTP/1.1
Authorization: {{authToken}}

