@contentType = application/json

### ======== login ===========

# @name login
POST http://{{host}}/api/login HTTP/1.1
content-type: {{contentType}}

{
    "email": "wyh@qq.com",
    "password": "123456"
}

### 登录成功后的 token
@authToken = Bearer {{login.response.body.$.data.token}}

### ============================
### ======== users ===========

### 获取当前登录用户信息

GET http://{{host}}/api/users HTTP/1.1
Authorization: {{authToken}}

### 新增/注册

POST http://{{host}}/api/users HTTP/1.1
content-type: {{contentType}}
Authorization: {{authToken}}

{
    "name": "wyh",  
    "email": "wyh@qq.com",
    "password": "123456",
    "password_confirmation": "123456"
}

### 详情 by id

GET http://{{host}}/api/users/1 HTTP/1.1
Authorization: {{authToken}}

### 修改 by id

PUT http://{{host}}/api/users/3 HTTP/1.1
content-type: {{contentType}}
Authorization: {{authToken}}

{
    "name": "test333",  
    "password": "123456",
    "password_confirmation": "123456"
}

### 删除 by id

DELETE  http://{{host}}/api/users/4 HTTP/1.1
Authorization: {{authToken}}

### ============================
### ======== article ===========

### 列表

GET http://{{host}}/api/articles?size=3 HTTP/1.1
Authorization: {{authToken}}

### 新增

POST http://{{host}}/api/articles HTTP/1.1
content-type: {{contentType}}
Authorization: {{authToken}}

{
    "title": "一篇文章10"
}

### 详情 by id

GET http://{{host}}/api/articles/10 HTTP/1.1
Authorization: {{authToken}}

### 修改 by id

PUT http://{{host}}/api/articles/9 HTTP/1.1
content-type: {{contentType}}
Authorization: {{authToken}}

{
    "title": "一篇文章09"
}

### 删除 by id

DELETE  http://{{host}}/api/articles/5 HTTP/1.1
Authorization: {{authToken}}

### ============================
### ======== article.comments ===========

@article_id = 1

### 列表

GET http://{{host}}/api/article/{{article_id}}/comments?size=5 HTTP/1.1
Authorization: {{authToken}}

### 新增

POST http://{{host}}/api/article/{{article_id}}/comments HTTP/1.1
content-type: {{contentType}}
Authorization: {{authToken}}

{
    "content": "感谢支持",
    "to_user_id": 9
}

### 详情 by id

GET http://{{host}}/api/comments/4 HTTP/1.1
Authorization: {{authToken}}

### 修改 by id

PUT http://{{host}}/api/comments/5 HTTP/1.1
content-type: {{contentType}}
Authorization: {{authToken}}

{
    "content": "感谢支持02"
}

### 删除 by id

DELETE  http://{{host}}/api/comments/5 HTTP/1.1
Authorization: {{authToken}}
